// pico/src/features/chat/components/MessageList.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";
  import { ArrowDown } from "@lucide/svelte";
  import { chatLogState } from "@/features/chat/model/chat-log.state.svelte";
  import UserMessageView from "@/features/chat/components/UserMessage.svelte";
  import AssistantMessageView from "@/features/chat/components/AssistantMessage.svelte";
  import ToolCallView from "@/features/chat/components/ToolCall.svelte";
  import CompactionMessageView from "@/features/chat/components/CompactionMessage.svelte";
  import AgentThinkingIndicator from "@/features/chat/components/AgentThinkingIndicator.svelte";
  import { activeSessionState } from "@/features/chat/model/active-session.state.svelte";
  import { markSessionOpen } from "@/shared/lib/session-open-timing";
  import { Button } from "@/shared/ui/button";

  let { sessionId }: { sessionId: string } = $props();

  const STICK_THRESHOLD_PX = 64;

  let scroller = $state<HTMLDivElement | null>(null);
  let bottomSentinel = $state<HTMLDivElement | null>(null);
  let stuckToBottom = $state(true);
  let hasNewActivity = $state(false);
  let lastActivityVersion = $state(chatLogState.activityVersion);
  let lastThinkingIndicatorVisible = false;
  let firstRenderMarked = false;

  const latestEntry = $derived.by(() => chatLogState.entries[chatLogState.entries.length - 1]);
  const showThinkingIndicator = $derived.by(() => {
    if (activeSessionState.status !== "thinking") return false;

    const latest = latestEntry;
    if (!latest) return true;
    if (latest.kind === "assistant") return false;
    if (latest.kind === "tool_call" && latest.status === "running") return false;
    if (latest.kind === "compaction" && latest.status === "running") return false;
    return true;
  });

  function distanceFromBottom(): number {
    if (!scroller) return 0;
    return scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight;
  }

  function pinToBottom(): void {
    if (!scroller) return;
    scroller.scrollTop = scroller.scrollHeight;
    stuckToBottom = true;
    hasNewActivity = false;
  }

  function applyScrollToLatest(behavior: ScrollBehavior): void {
    if (!scroller) return;
    bottomSentinel?.scrollIntoView({ block: "end", behavior });
    pinToBottom();
  }

  let settleRaf: number | null = null;

  async function scrollToLatest(behavior: ScrollBehavior = "smooth"): Promise<void> {
    if (!scroller) return;
    await tick();

    if (settleRaf !== null) cancelAnimationFrame(settleRaf);
    let remainingFrames = 5;
    const step = () => {
      applyScrollToLatest(remainingFrames === 5 ? behavior : "auto");
      remainingFrames -= 1;
      settleRaf = remainingFrames > 0 ? requestAnimationFrame(step) : null;
    };
    step();
  }

  function onScroll(): void {
    const stuck = distanceFromBottom() < STICK_THRESHOLD_PX;
    stuckToBottom = stuck;
    if (stuck) hasNewActivity = false;
  }

  // Streamed deltas should gently preserve the bottom lock, not run the
  // multi-frame settle path used for keyboard/composer resize.
  let scrollRaf: number | null = null;

  function scheduleScrollSync(): void {
    if (scrollRaf !== null) return;
    scrollRaf = requestAnimationFrame(() => {
      scrollRaf = null;
      if (stuckToBottom) pinToBottom();
      else hasNewActivity = true;
    });
  }

  onMount(() => {
    void scrollToLatest("auto");

    let lastScrollerHeight = scroller?.clientHeight ?? 0;
    const resizeObserver = new ResizeObserver(() => {
      if (!scroller) return;

      const nextHeight = scroller.clientHeight;
      const lostHeight = Math.max(0, lastScrollerHeight - nextHeight);
      lastScrollerHeight = nextHeight;

      // When the keyboard/composer changes height, keep the latest message pinned
      // only if the user was already following the bottom of the chat.
      if (stuckToBottom || distanceFromBottom() <= STICK_THRESHOLD_PX + lostHeight) {
        void scrollToLatest("auto");
      }
    });
    if (scroller) resizeObserver.observe(scroller);

    return () => {
      resizeObserver.disconnect();
      if (scrollRaf !== null) cancelAnimationFrame(scrollRaf);
      if (settleRaf !== null) cancelAnimationFrame(settleRaf);
    };
  });

  $effect(() => {
    if (chatLogState.entries.length > 0 && !firstRenderMarked) {
      firstRenderMarked = true;
      void tick().then(() => requestAnimationFrame(() => markSessionOpen(sessionId, "first-render")));
    }
  });

  $effect(() => {
    const version = chatLogState.activityVersion;
    const indicatorVisible = showThinkingIndicator;
    const logChanged = version !== lastActivityVersion;
    const indicatorAppeared = indicatorVisible && !lastThinkingIndicatorVisible;

    lastActivityVersion = version;
    lastThinkingIndicatorVisible = indicatorVisible;

    if (logChanged || indicatorAppeared) scheduleScrollSync();
  });
</script>

<div class="relative min-h-0 flex-1 overflow-hidden">
  <div bind:this={scroller} onscroll={onScroll} class="scroll-momentum h-full overflow-y-auto py-2" style="padding-bottom: 0.5rem">
    {#each chatLogState.entries as entry (entry.id)}
      <div class="msg-cv">
        {#if entry.kind === "user"}
          <UserMessageView msg={entry} {sessionId} />
        {:else if entry.kind === "assistant"}
          <AssistantMessageView msg={entry} {sessionId} />
        {:else if entry.kind === "tool_call"}
          <ToolCallView msg={entry} />
        {:else if entry.kind === "compaction"}
          <CompactionMessageView msg={entry} />
        {/if}
      </div>
    {/each}
    {#if showThinkingIndicator}
      <div class="msg-cv">
        <AgentThinkingIndicator />
      </div>
    {/if}
    <div bind:this={bottomSentinel} aria-hidden="true"></div>
  </div>

  {#if !stuckToBottom}
    <Button
      type="button"
      variant={hasNewActivity ? "default" : "outline"}
      size="sm"
      onpointerdown={(event) => event.preventDefault()}
      onclick={() => void scrollToLatest("auto")}
      class={`type-meta absolute right-3 z-30 h-auto rounded-full px-3 py-1.5 shadow-lg backdrop-blur-md ${hasNewActivity ? "active:opacity-85" : "border-[color:var(--color-border-strong)] bg-[color:var(--color-surface)]/95 text-[color:var(--color-fg)] active:bg-[color:var(--color-surface-2)]"}`}
      style="bottom: 0.75rem"
      aria-label={hasNewActivity ? "Scroll to new messages" : "Scroll to latest message"}
    >
      <ArrowDown class="size-3.5" />
      <span>{hasNewActivity ? "new" : "latest"}</span>
    </Button>
  {/if}
</div>

// pi-mobile/src/components/chat/MessageList.tsx
import {
  For,
  Show,
  createEffect,
  createSignal,
  on,
  onCleanup,
  onMount,
  type JSX,
} from "solid-js";
import { ArrowDown } from "lucide-solid";
import { entries } from "~/stores/sessions";
import { ensureKeyboardTracking, keyboardHeight } from "~/lib/keyboard";
import UserMessageView from "./UserMessage";
import AssistantMessageView from "./AssistantMessage";
import ToolCallView from "./ToolCall";
import PermissionGate from "./PermissionGate";

/** Px from the bottom within which we consider the user "stuck to bottom". */
const STICK_THRESHOLD_PX = 64;

export default function MessageList(): JSX.Element {
  let scroller!: HTMLDivElement;
  const [stuckToBottom, setStuckToBottom] = createSignal(true);
  const [hasNewActivity, setHasNewActivity] = createSignal(false);

  ensureKeyboardTracking();

  function distanceFromBottom(): number {
    return scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight;
  }

  function scrollToLatest(behavior: ScrollBehavior = "smooth") {
    scroller.scrollTo({ top: scroller.scrollHeight, behavior });
    setStuckToBottom(true);
    setHasNewActivity(false);
  }

  // Track whether the user is near the bottom. If they scroll up, we stop
  // auto-scrolling so they can read past output without getting yanked.
  function onScroll() {
    const stuck = distanceFromBottom() < STICK_THRESHOLD_PX;
    setStuckToBottom(stuck);
    if (stuck) setHasNewActivity(false);
  }

  onMount(() => {
    scroller.addEventListener("scroll", onScroll, { passive: true });
    scrollToLatest("auto");
  });
  onCleanup(() => scroller?.removeEventListener("scroll", onScroll));

  // Total content length is a cheap-to-compute reactive signal that captures
  // both "new entry pushed" and "streaming assistant text grew".
  const contentLength = () => {
    let n = entries().length;
    for (const e of entries()) {
      if (e.kind === "assistant") n += e.text.length;
    }
    return n;
  };

  createEffect(
    on(
      contentLength,
      () => {
        if (stuckToBottom()) {
          scrollToLatest("auto");
        } else {
          setHasNewActivity(true);
        }
      },
      { defer: true },
    ),
  );

  return (
    <div class="relative min-h-0 flex-1">
      <div
        ref={scroller}
        class="scroll-momentum h-full overflow-y-auto py-2"
        style={{ "padding-bottom": `calc(${keyboardHeight()}px + 0.5rem)` }}
      >
        <For each={entries()}>
          {(entry) => {
            switch (entry.kind) {
              case "user":
                return <UserMessageView msg={entry} />;
              case "assistant":
                return <AssistantMessageView msg={entry} />;
              case "tool_call":
                return <ToolCallView msg={entry} />;
              case "permission":
                return <PermissionGate req={entry} />;
            }
          }}
        </For>
      </div>

      <Show when={!stuckToBottom()}>
        <button
          type="button"
          onClick={() => scrollToLatest()}
          class="absolute right-3 z-30 flex items-center gap-1.5 rounded-full border border-[color:var(--color-border-strong)] bg-[color:var(--color-surface)]/95 px-3 py-1.5 text-[11px] text-[color:var(--color-fg)] shadow-lg backdrop-blur-md active:bg-[color:var(--color-surface-2)]"
          style={{ bottom: `calc(${keyboardHeight()}px + 0.75rem)` }}
          aria-label="Scroll to latest message"
        >
          <ArrowDown size={13} />
          <span>{hasNewActivity() ? "new" : "latest"}</span>
        </button>
      </Show>
    </div>
  );
}
