// pi-mobile/src/features/chat/components/SessionAgentActions.svelte
<script lang="ts">
  import { MoreHorizontal } from "@lucide/svelte";
  import { createAgentActionsState } from "@/features/chat/actions/agent-actions.state.svelte";
  import AgentActionSheet from "@/features/chat/actions/AgentActionSheet.svelte";
  import AuthView from "@/features/chat/actions/AuthView.svelte";
  import CompactView from "@/features/chat/actions/CompactView.svelte";
  import MenuView from "@/features/chat/actions/MenuView.svelte";
  import SessionInfoView from "@/features/chat/actions/SessionInfoView.svelte";
  import SessionSettingsView from "@/features/chat/actions/SessionSettingsView.svelte";
  import TreeView from "@/features/chat/actions/TreeView.svelte";

  let { sessionId }: { sessionId: string } = $props();

  const actions = createAgentActionsState();
</script>

<button
  type="button"
  onclick={() => actions.setOpen(true)}
  class="flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)]"
  aria-label="Agent actions"
  title="Agent actions"
>
  <MoreHorizontal class="size-4" />
</button>

{#if actions.open}
  <AgentActionSheet
    bind:open={() => actions.open, (open) => actions.setOpen(open)}
    view={actions.view}
    error={actions.error}
    onBack={actions.back}
  >
    {#if actions.view === "menu"}
      <MenuView
        onModels={() => actions.setView("models")}
        onAuth={() => actions.setView("auth")}
        onCompact={() => actions.setView("compact")}
        onTree={() => actions.setView("tree")}
        onSettings={() => actions.setView("settings")}
        onInfo={() => actions.setView("info")}
      />
    {:else if actions.view === "models"}
      <SessionSettingsView {sessionId} onError={actions.setError} filterKeys={["model"]} />
    {:else if actions.view === "compact"}
      <CompactView {sessionId} onDone={actions.done} onError={actions.setError} />
    {:else if actions.view === "settings"}
      <SessionSettingsView {sessionId} onError={actions.setError} excludeKeys={["model"]} />
    {:else if actions.view === "tree"}
      <TreeView {sessionId} onDone={actions.done} onError={actions.setError} />
    {:else if actions.view === "info"}
      <SessionInfoView {sessionId} />
    {:else if actions.view === "auth"}
      <AuthView onError={actions.setError} />
    {/if}
  </AgentActionSheet>
{/if}

// pi-mobile/src/components/chat/SessionAgentActions.tsx
import { Show, createSignal, type JSX } from "solid-js";
import { MoreHorizontal } from "lucide-solid";
import { haptic } from "~/lib/haptics";
import AgentActionSheet from "~/components/chat/actions/AgentActionSheet";
import AuthView from "~/components/chat/actions/AuthView";
import CompactView from "~/components/chat/actions/CompactView";
import MenuView from "~/components/chat/actions/MenuView";
import ModelPicker from "~/components/chat/actions/ModelPicker";
import SessionInfoView from "~/components/chat/actions/SessionInfoView";
import SessionSettingsView from "~/components/chat/actions/SessionSettingsView";
import TreeView from "~/components/chat/actions/TreeView";
import type { AgentActionView } from "~/components/chat/actions/types";

interface Props {
  sessionId: string;
}

export default function SessionAgentActions(props: Props): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [view, setView] = createSignal<AgentActionView>("menu");
  const [error, setError] = createSignal<string | null>(null);

  function close() {
    setOpen(false);
    setView("menu");
    setError(null);
  }

  function back() {
    setView("menu");
    setError(null);
  }

  function done() {
    haptic.success();
    close();
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        class="flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)]"
        aria-label="Agent actions"
        title="Agent actions"
      >
        <MoreHorizontal size={16} />
      </button>

      <Show when={open()}>
        <AgentActionSheet view={view()} error={error()} onBack={back} onClose={close}>
          <Show when={view() === "menu"}>
            <MenuView
              onModels={() => setView("models")}
              onCompact={() => setView("compact")}
              onSettings={() => setView("settings")}
              onTree={() => setView("tree")}
              onInfo={() => setView("info")}
              onAuth={() => setView("auth")}
            />
          </Show>
          <Show when={view() === "models"}>
            <ModelPicker sessionId={props.sessionId} onError={setError} />
          </Show>
          <Show when={view() === "compact"}>
            <CompactView sessionId={props.sessionId} onDone={done} onError={setError} />
          </Show>
          <Show when={view() === "settings"}>
            <SessionSettingsView sessionId={props.sessionId} onError={setError} />
          </Show>
          <Show when={view() === "tree"}>
            <TreeView sessionId={props.sessionId} onDone={done} onError={setError} />
          </Show>
          <Show when={view() === "info"}>
            <SessionInfoView sessionId={props.sessionId} />
          </Show>
          <Show when={view() === "auth"}>
            <AuthView sessionId={props.sessionId} onError={setError} />
          </Show>
        </AgentActionSheet>
      </Show>
    </>
  );
}
