// pi-mobile/src/features/chat/components/InputBar.tsx
import { createSignal, createEffect, createResource, Show, For } from "solid-js";
import { MicOff, Square, ArrowUp, ImagePlus, ListTodo, Trash2, Plus } from "lucide-solid";
import { activeStatus } from "@/stores/sessions";
import { activeSend } from "@/stores/connection";
import { createSpeechRecognition } from "@/lib/speech";
import { chooseFromGallery } from "@/lib/image-picker";
import { haptic } from "@/lib/haptics";
import { createLongPress } from "@/lib/long-press";
import { clearSessionQueue, getSessionQueue } from "@/lib/api";
import { getBridgeUrl } from "@/lib/settings";
import type { ImageAttachment } from "@pi-mobile/protocol";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import SlashPalette from "./SlashPalette";
import ImageTray from "./ImageTray";

const LONG_PRESS_MS = 500;
const MAX_IMAGES = 4;

export default function InputBar(props: { sessionId: string }) {
  let ta: HTMLTextAreaElement | undefined;
  const [value, setValue] = createSignal("");
  const [composing, setComposing] = createSignal(false);
  const [holding, setHolding] = createSignal(false);
  const [paletteOpen, setPaletteOpen] = createSignal(false);
  const [actionsOpen, setActionsOpen] = createSignal(false);
  const [queueOpen, setQueueOpen] = createSignal(false);
  const [queueRefresh, setQueueRefresh] = createSignal(0);
  const [images, setImages] = createSignal<ImageAttachment[]>([]);

  const stt = createSpeechRecognition();

  let textBeforeRecording = "";
  createEffect(() => {
    if (stt.listening()) {
      const t = stt.transcript();
      const merged = textBeforeRecording
        ? `${textBeforeRecording.trimEnd()} ${t}`
        : t;
      setValue(merged);
      autoSize();
    }
  });

  const busy = () =>
    activeStatus() === "thinking" || activeStatus() === "tool";
  const hasText = () => value().trim().length > 0;
  const hasSendable = () => hasText() || images().length > 0;
  const canSend = () => activeSend() !== null;
  const [queueState] = createResource(
    () => `${props.sessionId}:${queueRefresh()}:${activeStatus()}`,
    async () => {
      const baseUrl = await getBridgeUrl();
      return getSessionQueue(baseUrl, props.sessionId);
    },
  );
  const queueCount = () =>
    (queueState()?.steering.length ?? 0) + (queueState()?.followUp.length ?? 0);
  const refreshQueueCount = () => setQueueRefresh((n) => n + 1);

  function autoSize() {
    if (!ta) return;
    ta.style.height = "auto";
    ta.style.height = Math.min(ta.scrollHeight, 180) + "px";
  }

  function submit(mode: "steer" | "follow_up") {
    const v = value().trim();
    const imgs = images();
    const send = activeSend();
    if ((!v && imgs.length === 0) || !send) return;
    const queued = busy();
    send({
      t: "send",
      text: v,
      mode,
      ...(imgs.length > 0 ? { images: imgs } : {}),
    });
    setValue("");
    setImages([]);
    textBeforeRecording = "";
    autoSize();
    if (queued) window.setTimeout(refreshQueueCount, 120);
    haptic.light();
  }

  function interrupt() {
    activeSend()?.({ t: "interrupt" });
  }

  async function toggleMic() {
    if (stt.listening()) {
      await stt.stop();
    } else {
      textBeforeRecording = value();
      await stt.start();
    }
  }

  function insertCommand(text: string) {
    const current = value();
    const slash = current.lastIndexOf("/");
    const before = slash >= 0 ? current.slice(0, slash) : current;
    const prefix = before.length === 0 || /\s$/.test(before) ? before : `${before} `;
    setValue(prefix + text);
    autoSize();
    setPaletteOpen(false);
    queueMicrotask(() => ta?.focus());
  }

  function handleInput(next: string) {
    setValue(next);
    autoSize();

    const slash = next.lastIndexOf("/");
    if (slash < 0) return;

    const before = slash === 0 ? "" : next[slash - 1];
    const token = next.slice(slash);
    if ((slash === 0 || /\s/.test(before)) && !/\s/.test(token.slice(1))) {
      setPaletteOpen(true);
    }
  }

  const sendPress = createLongPress({
    delayMs: LONG_PRESS_MS,
    enabled: () => hasSendable() && canSend(),
    onStart: () => setHolding(true),
    onCancel: () => setHolding(false),
    onLongPress: () => {
      haptic.medium();
      submit("follow_up");
    },
  });

  function handleClick() {
    if (sendPress.consumeClick()) return;
    submit("steer");
  }

  async function pickImages() {
    try {
      const remaining = MAX_IMAGES - images().length;
      if (remaining <= 0) return;
      const picked = await chooseFromGallery({ limit: remaining });
      if (picked.length > 0) {
        setImages((prev) => [...prev, ...picked].slice(0, MAX_IMAGES));
      }
    } catch (e) {
      console.warn("[input-bar] image pick failed:", e);
    }
  }

  function removeImage(index: number) {
    setImages((prev) => prev.filter((_, i) => i !== index));
  }

  return (
    <div
      class="hairline-t sticky bottom-0 z-20 bg-[color:var(--color-bg)]/95 backdrop-blur-md"
      style={{ "padding-bottom": "env(safe-area-inset-bottom)" }}
    >
      <ImageTray images={images()} onRemove={removeImage} />

      <div class="flex items-start gap-1.5 px-2 py-2">
        <button
          type="button"
          onClick={() => {
            refreshQueueCount();
            setActionsOpen(true);
          }}
          class="relative flex h-9 w-9 shrink-0 items-center justify-center rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)]"
          aria-label="More input actions"
          title="More input actions"
        >
          <Plus size={15} />
          <Show when={queueCount() > 0}>
            <span class="absolute right-0.5 top-0.5 flex min-w-4 translate-x-1/3 -translate-y-1/3 items-center justify-center rounded-full border border-[color:var(--color-bg)] bg-[color:var(--color-accent)] px-1 py-0.5 text-[9px] font-medium leading-none text-[color:var(--color-bg)]">
              {queueCount() > 99 ? "99+" : queueCount()}
            </span>
          </Show>
        </button>

        <div class="min-h-9 flex-1 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] focus-within:border-[color:var(--color-border-strong)]">
          <textarea
            ref={ta}
            value={value()}
            onInput={(e) => handleInput(e.currentTarget.value)}
            onCompositionStart={() => setComposing(true)}
            onCompositionEnd={() => setComposing(false)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey && !composing()) {
                e.preventDefault();
                submit("steer");
              }
            }}
            rows="1"
            class="w-full resize-none bg-transparent px-3 py-[7px] text-[13px] leading-[20px] text-[color:var(--color-fg)] focus:outline-none"
          />
        </div>

        <Show
          when={stt.listening()}
          fallback={
            <>
              <Show when={busy()}>
                <Button
                  type="button"
                  size="icon"
                  variant="default"
                  onClick={interrupt}
                  aria-label="Stop"
                  title="Stop the current turn"
                  class="bg-[color:var(--color-fg)] text-[color:var(--color-bg)] hover:bg-[color:var(--color-fg)] active:opacity-80"
                >
                  <Square size={11} fill="currentColor" />
                </Button>
              </Show>

              <Button
                type="button"
                size="icon"
                variant="default"
                onClick={handleClick}
                onPointerDown={(e) => sendPress.start(e)}
                onPointerUp={sendPress.end}
                onPointerLeave={sendPress.end}
                onPointerCancel={sendPress.end}
                disabled={!hasSendable() || !canSend()}
                classList={{
                  "scale-95": holding(),
                }}
                class="rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] text-[color:var(--color-bg)] transition-transform duration-100 hover:bg-[color:var(--color-accent)] active:opacity-80 disabled:bg-[color:var(--color-surface)] disabled:text-[color:var(--color-fg-faint)] disabled:opacity-100"
                aria-label={busy() ? "Queue message (hold to follow-up)" : "Send"}
                title={
                  hasSendable()
                    ? busy()
                      ? "Tap to steer · hold to queue follow-up"
                      : "Send (hold to queue as follow-up)"
                    : "Draft a message to send"
                }
              >
                <ArrowUp size={14} strokeWidth={2.5} />
              </Button>
            </>
          }
        >
          <Button
            type="button"
            size="icon"
            onClick={toggleMic}
            class="rounded-[var(--radius-sm)] bg-[color:var(--color-danger)] text-[color:var(--color-bg)] pulse-accent active:opacity-80"
            aria-label="Stop dictation"
            title="Stop dictation"
          >
            <MicOff size={14} />
          </Button>
        </Show>
      </div>

      <SlashPalette
        open={paletteOpen()}
        sessionId={props.sessionId}
        onCancel={() => setPaletteOpen(false)}
        onPick={insertCommand}
      />
      <InputActionsSheet
        open={actionsOpen()}
        queueCount={queueCount()}
        imagesFull={images().length >= MAX_IMAGES}
        maxImages={MAX_IMAGES}
        onAttachImage={() => {
          setActionsOpen(false);
          void pickImages();
        }}
        onOpenQueue={() => {
          setActionsOpen(false);
          refreshQueueCount();
          setQueueOpen(true);
        }}
        onClose={() => setActionsOpen(false)}
      />
      <QueueSheet
        open={queueOpen()}
        sessionId={props.sessionId}
        onChanged={refreshQueueCount}
        onClose={() => {
          setQueueOpen(false);
          refreshQueueCount();
        }}
      />
    </div>
  );
}

function InputActionsSheet(props: {
  open: boolean;
  queueCount: number;
  imagesFull: boolean;
  maxImages: number;
  onAttachImage: () => void;
  onOpenQueue: () => void;
  onClose: () => void;
}) {
  function handleOpenChange(open: boolean) {
    if (!open) props.onClose();
  }

  return (
    <Show when={props.open}>
      <Sheet open onOpenChange={handleOpenChange}>
        <SheetContent
          position="bottom"
          class="flex flex-col !max-h-[45dvh] !overflow-hidden gap-0 rounded-t-[12px] border-[color:var(--color-border-strong)] bg-[color:var(--color-bg)] p-0 text-[color:var(--color-fg)] shadow-none"
          style={{ "padding-bottom": "calc(env(safe-area-inset-bottom) + 0.5rem)" }}
        >
          <SheetHeader class="hairline-b space-y-0 px-3 py-3 pr-12 text-left">
            <SheetTitle class="min-w-0 flex-1 px-1 text-[13px] font-medium">add</SheetTitle>
          </SheetHeader>
          <div class="grid grid-cols-2 gap-2 px-3 py-3">
          <button
            type="button"
            onClick={props.onAttachImage}
            disabled={props.imagesFull}
            class="flex min-h-20 flex-col items-center justify-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-3 text-center active:bg-[color:var(--color-surface-2)] disabled:opacity-40"
          >
            <ImagePlus size={18} class="text-[color:var(--color-fg-muted)]" />
            <span class="text-[12px] font-medium">image</span>
            <span class="text-[10px] text-[color:var(--color-fg-faint)]">
              {props.imagesFull ? `max ${props.maxImages}` : "attach photo"}
            </span>
          </button>

          <button
            type="button"
            onClick={props.onOpenQueue}
            class="flex min-h-20 flex-col items-center justify-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-3 text-center active:bg-[color:var(--color-surface-2)]"
          >
            <span class="relative">
              <ListTodo size={18} class="text-[color:var(--color-fg-muted)]" />
              <Show when={props.queueCount > 0}>
                <span class="absolute -right-2 -top-2 flex min-w-4 items-center justify-center rounded-full bg-[color:var(--color-accent)] px-1 py-0.5 text-[9px] font-medium leading-none text-[color:var(--color-bg)]">
                  {props.queueCount > 99 ? "99+" : props.queueCount}
                </span>
              </Show>
            </span>
            <span class="text-[12px] font-medium">queue</span>
            <span class="text-[10px] text-[color:var(--color-fg-faint)]">
              {props.queueCount > 0 ? `${props.queueCount} pending` : "empty"}
            </span>
          </button>
          </div>
        </SheetContent>
      </Sheet>
    </Show>
  );
}

function QueueSheet(props: {
  open: boolean;
  sessionId: string;
  onChanged: () => void;
  onClose: () => void;
}) {
  const [refresh, setRefresh] = createSignal(0);
  const [clearing, setClearing] = createSignal(false);
  const [queue] = createResource(
    () => (props.open ? `${props.sessionId}:${refresh()}` : null),
    async () => {
      const baseUrl = await getBridgeUrl();
      return getSessionQueue(baseUrl, props.sessionId);
    },
  );
  const total = () => (queue()?.steering.length ?? 0) + (queue()?.followUp.length ?? 0);

  async function clearQueuedMessages() {
    setClearing(true);
    try {
      const baseUrl = await getBridgeUrl();
      await clearSessionQueue(baseUrl, props.sessionId);
      setRefresh((n) => n + 1);
      props.onChanged();
    } finally {
      setClearing(false);
    }
  }

  function handleOpenChange(open: boolean) {
    if (!open) props.onClose();
  }

  return (
    <Show when={props.open}>
      <Sheet open onOpenChange={handleOpenChange}>
        <SheetContent
          position="bottom"
          class="flex flex-col !max-h-[75dvh] !overflow-hidden gap-0 rounded-t-[12px] border-[color:var(--color-border-strong)] bg-[color:var(--color-bg)] p-0 text-[color:var(--color-fg)] shadow-none"
          style={{ "padding-bottom": "calc(env(safe-area-inset-bottom) + 0.5rem)" }}
        >
          <SheetHeader class="hairline-b space-y-0 px-3 py-3 pr-12 text-left">
            <SheetTitle class="min-w-0 flex-1 px-1 text-[13px] font-medium">queued messages</SheetTitle>
          </SheetHeader>
          <div class="flex-1 overflow-y-auto px-3 py-3">
          <Show when={queue.loading}>
            <div class="text-[12px] text-[color:var(--color-fg-faint)]">loading queue…</div>
          </Show>
          <Show when={queue.error}>
            <div class="text-[12px] text-[color:var(--color-danger)]">{String(queue.error)}</div>
          </Show>
          <Show when={queue() && total() === 0}>
            <div class="rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] p-3 text-center text-[12px] text-[color:var(--color-fg-faint)]">no queued messages</div>
          </Show>
          <Show when={queue()}>
            {(q) => (
              <div class="space-y-3">
                <QueueSection label="steering" items={q().steering} />
                <QueueSection label="follow-up" items={q().followUp} />
              </div>
            )}
          </Show>
        </div>
        <Show when={total() > 0}>
          <div class="hairline-t px-3 py-2">
            <Button
              type="button"
              variant="destructive"
              disabled={clearing()}
              onClick={clearQueuedMessages}
              class="w-full bg-transparent text-[color:var(--color-danger)] hover:bg-[color:var(--color-surface)]"
            >
              <Trash2 size={13} />
              {clearing() ? "clearing…" : "clear queued messages"}
            </Button>
          </div>
        </Show>
        </SheetContent>
      </Sheet>
    </Show>
  );
}

function QueueSection(props: { label: string; items: string[] }) {
  return (
    <Show when={props.items.length > 0}>
      <div>
        <div class="label mb-1.5">{props.label}</div>
        <div class="space-y-1.5">
          <For each={props.items}>
            {(item) => (
              <div class="rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-2 text-[12px] text-[color:var(--color-fg)]">
                {item}
              </div>
            )}
          </For>
        </div>
      </div>
    </Show>
  );
}

// pico/src/features/chat/components/InputBar.svelte
<script lang="ts">
  import { onDestroy, onMount, untrack } from "svelte";
  import { ArrowUp, ImagePlus, ListTodo, Mic, MicOff, Plus, Square } from "@lucide/svelte";
  import type { ImageContent, SessionControls, SessionStats } from "@pico/protocol";
  import { activeSessionState } from "@/features/chat/model/active-session.state.svelte";
  import { chatLogState } from "@/features/chat/model/chat-log.state.svelte";
  import { chatQueueState } from "@/features/chat/model/chat-queue.state.svelte";
  import { queuedMessageActionsState } from "@/features/chat/model/queued-message-actions.state.svelte";
  import { createSpeechRecognitionState } from "@/shared/mobile/speech.svelte";
  import { pickImages } from "@/shared/mobile/image-picker";
  import { cloneImageContent, filesToImageContent } from "@/shared/mobile/image-content";
  import { haptics } from "@/shared/mobile/haptics";
  import { createLongPress } from "@/shared/gestures/long-press";
  import { clearSessionQueue, getSessionQueue, getSessionSettings } from "@/features/chat/api";
  import { hostIssueSummary } from "@/shared/lib/host-issues";
  import { runOnHost } from "@/shared/lib/rpc-client";
  import { formatCost } from "@/shared/lib/format";
  import { clearChatDraft, loadChatDraft, saveChatDraft } from "@/features/chat/model/chat-draft";
  import { Button } from "@/shared/ui/button";
  import * as Sheet from "@/shared/ui/sheet";
  import SheetHeader from "@/shared/components/SheetHeader.svelte";
  import ImageTray from "@/features/chat/components/ImageTray.svelte";
  import CompactContextSheet from "@/features/chat/components/CompactContextSheet.svelte";
  import QueuedMessagesSheet from "@/features/chat/components/QueuedMessagesSheet.svelte";
  import SessionSettingsView from "@/features/chat/actions/SessionSettingsView.svelte";
  import SlashCommandSuggestions from "@/features/chat/components/SlashCommandSuggestions.svelte";
  import { createSlashCommandsState, type CommandEntry, type SlashCommandCompletion } from "@/features/chat/components/slash-commands.state.svelte";

  const LONG_PRESS_MS = 500;
  const MAX_IMAGES = 4;
  const DRAFT_SAVE_DELAY_MS = 350;

  let {
    hostId,
    sessionId,
    contextStats,
  }: {
    hostId: string;
    sessionId: string;
    contextStats?: { cost: number; usage: NonNullable<SessionStats["contextUsage"]> };
  } = $props();

  let controls = $state<SessionControls | null>(null);
  let modelOpen = $state(false);

  let textarea = $state<HTMLTextAreaElement | null>(null);
  let value = $state("");
  let cursor = $state(0);
  let composing = $state(false);
  let holding = $state(false);
  let ignoreNextSendClick = false;
  let sendPointerId: number | null = null;
  let actionsOpen = $state(false);
  let compactOpen = $state(false);
  let queueOpen = $state(false);
  let images = $state<ImageContent[]>([]);
  let queueLoading = $state(false);
  let queueError = $state<string | null>(null);
  let clearing = $state(false);
  let queueRequestId = 0;
  let draftLoadRequestId = 0;
  let draftLoadedFor = $state<string | null>(null);
  let draftEditVersion = 0;
  let lastRecallRequestId = 0;

  const stt = createSpeechRecognitionState();
  const slashCommands = createSlashCommandsState(
    () => hostId,
    () => sessionId,
    () => value,
    () => cursor,
  );
  let textBeforeRecording = "";

  onMount(() => {
    void stt.checkAvailability();
  });

  onDestroy(() => {
    clearSendPointerListeners();
    stt.destroy();
  });

  const busy = $derived(activeSessionState.status === "thinking" || activeSessionState.status === "tool");
  const hasText = $derived(value.trim().length > 0);
  const hasSendable = $derived(hasText || images.length > 0);
  const canSend = $derived(activeSessionState.send !== null);
  const queue = $derived(chatQueueState.get(hostId, sessionId));
  const queueCount = $derived(chatQueueState.count(hostId, sessionId));
  const contextPercent = $derived(
    contextStats && contextStats.usage.percent !== null ? Math.round(contextStats.usage.percent) : null,
  );

  const modelControl = $derived(controls?.controls.find((control) => control.key === "model"));
  const modelLabel = $derived.by(() => {
    const mc = modelControl;
    if (!mc || mc.kind !== "select") return null;
    return mc.options.find((option) => option.value === mc.value)?.label ?? mc.value;
  });

  async function loadControls(): Promise<void> {
    try {
      controls = await runOnHost(hostId, getSessionSettings(sessionId));
    } catch {
      controls = null;
    }
  }

  // Refresh the model chip on session change and after the picker sheet closes.
  $effect(() => {
    hostId;
    sessionId;
    if (modelOpen) return;
    untrack(() => void loadControls());
  });

  $effect(() => {
    if (!stt.listening) return;
    const transcript = stt.transcript;
    draftEditVersion += 1;
    value = textBeforeRecording ? `${textBeforeRecording.trimEnd()} ${transcript}` : transcript;
  });

  $effect(() => {
    const key = `${hostId}:${sessionId}`;
    untrack(() => {
      void restoreDraft(hostId, sessionId, key);
      void syncQueue();
    });
  });

  $effect(() => {
    const request = queuedMessageActionsState.recallRequest;
    if (!request || request.hostId !== hostId || request.sessionId !== sessionId || request.id === lastRecallRequestId) return;

    lastRecallRequestId = request.id;
    draftEditVersion += 1;
    value = request.text;
    cursor = request.text.length;
    images = cloneImageContent(request.images) ?? [];
    textBeforeRecording = "";
    requestAnimationFrame(() => {
      textarea?.focus();
      textarea?.setSelectionRange(request.text.length, request.text.length);
    });
  });

  $effect(() => {
    const key = `${hostId}:${sessionId}`;
    const draftText = value;
    if (draftLoadedFor !== key) return;

    const timer = window.setTimeout(() => {
      void saveChatDraft(hostId, sessionId, draftText);
    }, DRAFT_SAVE_DELAY_MS);

    return () => window.clearTimeout(timer);
  });

  $effect(() => {
    if (!actionsOpen) return;

    const closeOnOutsidePointerDown = (event: PointerEvent) => {
      const target = event.target;
      if (target instanceof Element && target.closest("[data-input-actions]")) return;
      actionsOpen = false;
    };

    window.addEventListener("pointerdown", closeOnOutsidePointerDown, { capture: true });
    return () => window.removeEventListener("pointerdown", closeOnOutsidePointerDown, { capture: true });
  });

  function autosize(node: HTMLTextAreaElement, _value: string) {
    const resize = () => {
      node.style.height = "auto";
      node.style.height = `${Math.min(node.scrollHeight, 180)}px`;
    };

    resize();
    return { update: resize };
  }

  function updateCursor(node: HTMLTextAreaElement): void {
    cursor = node.selectionStart ?? value.length;
  }

  async function restoreDraft(nextHostId: string, nextSessionId: string, key: string): Promise<void> {
    const requestId = ++draftLoadRequestId;
    const editVersion = draftEditVersion;
    draftLoadedFor = null;
    value = "";
    cursor = 0;
    images = [];
    textBeforeRecording = "";

    const draftText = await loadChatDraft(nextHostId, nextSessionId).catch(() => "");
    if (requestId !== draftLoadRequestId || key !== `${hostId}:${sessionId}`) return;

    if (draftEditVersion === editVersion) {
      value = draftText;
    }
    draftLoadedFor = key;
  }

  function submit(mode: "steer" | "follow_up"): void {
    const text = value.trim();
    const send = activeSessionState.send;
    const sentImages = cloneImageContent(images);
    if ((!text && !sentImages) || !send) return;
    const event = {
      t: "send" as const,
      text,
      mode,
      ...(sentImages ? { images: sentImages } : {}),
      clientId: crypto.randomUUID(),
    };
    send(event);
    chatLogState.appendLocalEcho(hostId, sessionId, event);
    value = "";
    cursor = 0;
    images = [];
    textBeforeRecording = "";
    void clearChatDraft(hostId, sessionId);
    haptics.light();
  }

  function interrupt(): void {
    activeSessionState.send?.({ t: "interrupt" });
  }

  async function toggleMic(): Promise<void> {
    if (stt.listening) {
      await stt.stop();
    } else {
      textBeforeRecording = value;
      await stt.start();
    }
  }

  // Tap sends/steers; long-press queues a follow-up — pi's alt+enter, as a touch gesture.
  const sendPress = createLongPress({
    delayMs: LONG_PRESS_MS,
    enabled: () => hasSendable && canSend,
    onStart: () => (holding = true),
    onCancel: () => (holding = false),
    onLongPress: () => {
      holding = false;
      haptics.medium();
      submit("follow_up");
    },
  });

  function clearSendPointerListeners(): void {
    window.removeEventListener("pointerup", handleWindowSendPointerUp, { capture: true });
    window.removeEventListener("pointercancel", handleWindowSendPointerCancel, { capture: true });
  }

  function handleSendPointerDown(event: PointerEvent): void {
    if (!hasSendable || !canSend) return;

    // Keep the textarea focused so the native keyboard/WebView layout doesn't
    // move under the finger before the tap completes.
    event.preventDefault();
    clearSendPointerListeners();
    ignoreNextSendClick = false;
    sendPointerId = event.pointerId;
    sendPress.start(event);
    window.addEventListener("pointerup", handleWindowSendPointerUp, { capture: true });
    window.addEventListener("pointercancel", handleWindowSendPointerCancel, { capture: true });
  }

  function finishSendPointer(): void {
    clearSendPointerListeners();
    sendPointerId = null;
    ignoreNextSendClick = true;
    sendPress.end();
    if (sendPress.consumeClick()) return;
    submit("steer");
  }

  function handleWindowSendPointerUp(event: PointerEvent): void {
    if (sendPointerId !== null && event.pointerId !== sendPointerId) return;
    event.preventDefault();
    finishSendPointer();
  }

  function handleWindowSendPointerCancel(event: PointerEvent): void {
    if (sendPointerId !== null && event.pointerId !== sendPointerId) return;
    clearSendPointerListeners();
    sendPointerId = null;
    sendPress.end();
  }

  function handleSendClick(): void {
    if (ignoreNextSendClick) {
      ignoreNextSendClick = false;
      return;
    }
    if (sendPress.consumeClick()) return;
    submit("steer");
  }

  function applyCommandCompletion(completion: SlashCommandCompletion): void {
    value = completion.value;
    cursor = completion.cursor;
    draftEditVersion += 1;
    requestAnimationFrame(() => {
      textarea?.focus();
      textarea?.setSelectionRange(completion.cursor, completion.cursor);
    });
  }

  function completeCommand(entry: CommandEntry): void {
    applyCommandCompletion(slashCommands.complete(entry));
  }

  function handleCommandKey(event: KeyboardEvent): boolean {
    const completion = slashCommands.handleKey(event);
    if (!completion) return event.defaultPrevented;
    applyCommandCompletion(completion);
    return true;
  }

  function toggleActions(): void {
    actionsOpen = !actionsOpen;
  }

  async function runAction(action: () => void | Promise<void>): Promise<void> {
    actionsOpen = false;
    await action();
  }

  function addImages(next: readonly ImageContent[]): void {
    const cloned = cloneImageContent(next);
    if (!cloned) return;
    images = [...images, ...cloned].slice(0, MAX_IMAGES);
    draftEditVersion += 1;
  }

  async function attachImages(): Promise<void> {
    try {
      const remaining = MAX_IMAGES - images.length;
      if (remaining <= 0) return;
      addImages(await pickImages({ limit: remaining }));
    } catch (error) {
      console.warn("[input-bar] image pick failed:", error);
    }
  }

  async function handlePaste(event: ClipboardEvent): Promise<void> {
    const files = Array.from(event.clipboardData?.files ?? []).filter((file) => file.type.startsWith("image/"));
    const remaining = MAX_IMAGES - images.length;
    if (files.length === 0 || remaining <= 0) return;
    event.preventDefault();

    try {
      addImages(await filesToImageContent(files, remaining));
    } catch (error) {
      console.warn("[input-bar] image paste failed:", error);
    }
  }

  function removeImage(index: number): void {
    images = images.filter((_, candidate) => candidate !== index);
    draftEditVersion += 1;
  }

  async function syncQueue(options: { showLoading?: boolean } = {}): Promise<void> {
    const requestId = ++queueRequestId;
    if (options.showLoading) {
      queueLoading = true;
      queueError = null;
    }

    try {
      const next = await runOnHost(hostId, getSessionQueue(sessionId));
      if (requestId !== queueRequestId) return;
      chatQueueState.set(hostId, sessionId, next);
    } catch (error) {
      if (requestId !== queueRequestId || !options.showLoading) return;
      queueError = hostIssueSummary(error);
    } finally {
      if (requestId === queueRequestId && options.showLoading) queueLoading = false;
    }
  }

  function loadQueue(): Promise<void> {
    return syncQueue({ showLoading: true });
  }

  async function clearQueuedMessages(): Promise<void> {
    clearing = true;
    try {
      await runOnHost(hostId, clearSessionQueue(sessionId));
      chatQueueState.clear(hostId, sessionId);
    } finally {
      clearing = false;
    }
  }
</script>

<div class="pointer-events-auto relative z-20 shrink-0" style="padding-bottom: env(safe-area-inset-bottom)">
  {#if slashCommands.query !== null}
    <SlashCommandSuggestions
      entries={slashCommands.matches}
      selectedIndex={slashCommands.selectedIndex}
      loading={slashCommands.loading}
      error={slashCommands.error}
      onPick={completeCommand}
      onSelect={slashCommands.select}
    />
  {/if}

  <ImageTray {images} onRemove={removeImage} />

  <!--
    One composer card (Claude-style): the textarea on top, a control row beneath
    it inside the same card. Visible controls live in the row rather than hidden
    in a menu — context budget as a chip, the rest as icon buttons.
  -->
  <div class="m-2 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] focus-within:border-[color:var(--color-border-strong)]">
    <textarea
      bind:this={textarea}
      bind:value
      use:autosize={value}
      oninput={(event) => {
        draftEditVersion += 1;
        updateCursor(event.currentTarget);
      }}
      onpaste={(event) => void handlePaste(event)}
      onclick={(event) => updateCursor(event.currentTarget)}
      onkeyup={(event) => updateCursor(event.currentTarget)}
      onselect={(event) => updateCursor(event.currentTarget)}
      oncompositionstart={() => (composing = true)}
      oncompositionend={(event) => {
        composing = false;
        updateCursor(event.currentTarget);
      }}
      onkeydown={(event) => {
        if (handleCommandKey(event)) return;
        if (event.key === "Enter" && !event.shiftKey && !composing) {
          event.preventDefault();
          submit("steer");
        }
      }}
      rows="1"
      placeholder="ask, or / for commands"
      class="type-input w-full resize-none bg-transparent px-3 pt-2 pb-1 text-[color:var(--color-fg)] placeholder:text-[color:var(--color-fg-faint)] focus:outline-none"
    ></textarea>

    <div class="flex items-center gap-1 px-1.5 pb-1.5">
      <div class="relative shrink-0" data-input-actions>
        {#if actionsOpen}
          <div class="absolute bottom-[calc(100%+0.75rem)] left-0 z-40 flex flex-col gap-1.5">
            {@render ActionFab("Attach image", images.length >= MAX_IMAGES, () => runAction(attachImages), "image")}
            {@render ActionFab("Dictate", stt.available === false, () => runAction(toggleMic), "mic")}
          </div>
        {/if}
        <Button type="button" variant="ghost" size="icon" onpointerdown={(event) => event.preventDefault()} onclick={toggleActions} class="relative rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface-2)]" aria-label="More input actions" title="More input actions" aria-expanded={actionsOpen}>
          {#if actionsOpen}
            <span class="absolute h-7 w-7 rotate-45 rounded-[var(--radius-sm)] bg-[color:var(--color-surface-2)]" aria-hidden="true"></span>
          {/if}
          <Plus class={`relative size-4 transition-transform ${actionsOpen ? "rotate-45" : ""}`} />
        </Button>
      </div>

      {#if modelLabel}
        <button
          type="button"
          onpointerdown={(event) => event.preventDefault()}
          onclick={() => (modelOpen = true)}
          class="type-meta max-w-[12ch] shrink-0 truncate rounded-[var(--radius-sm)] px-2 py-1.5 text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface-2)]"
          aria-label="Model — tap to change"
          title="Change model"
        >
          {modelLabel}
        </button>
      {/if}

      {#if contextStats}
        <button
          type="button"
          onpointerdown={(event) => event.preventDefault()}
          onclick={() => (compactOpen = true)}
          class="type-meta shrink-0 rounded-[var(--radius-sm)] px-2 py-1.5 tabular-nums text-[color:var(--color-fg-faint)] active:bg-[color:var(--color-surface-2)]"
          aria-label="Context usage — tap to compact"
          title="Compact context"
        >
          {contextPercent !== null ? `${contextPercent}%` : "—"} · {formatCost(contextStats.cost)}
        </button>
      {/if}

      <div class="min-w-0 flex-1"></div>

      {#if queueCount > 0}
        <Button type="button" variant="ghost" size="icon" onclick={() => (queueOpen = true)} class="relative shrink-0 rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface-2)]" aria-label="Queued messages" title="Queued messages">
          <ListTodo class="size-4" />
          <span class="absolute right-0.5 top-0.5 flex min-w-4 translate-x-1/3 -translate-y-1/3 items-center justify-center rounded-full border border-[color:var(--color-surface)] bg-[color:var(--color-accent)] px-1 py-0.5 text-[0.625rem] font-medium leading-none text-[color:var(--color-bg)]">
            {queueCount > 99 ? "99+" : queueCount}
          </span>
        </Button>
      {/if}

      {#if stt.listening}
        <Button type="button" size="icon" onclick={toggleMic} class="rounded-[var(--radius-sm)] bg-[color:var(--color-danger)] text-[color:var(--color-bg)] pulse-accent active:opacity-80" aria-label="Stop dictation" title="Stop dictation">
          <MicOff class="size-3.5" />
        </Button>
      {:else}
        {#if busy}
          <Button type="button" variant="outline" size="icon" onclick={interrupt} aria-label="Stop" title="Stop the current turn" class="shrink-0 rounded-[var(--radius-sm)] active:opacity-80">
            <Square class="size-3" fill="currentColor" />
          </Button>
        {/if}
        <!-- Keep mounted after submit clears the draft so the follow-up click can't retarget to Stop. -->
        <Button
          type="button"
          size="icon-lg"
          onclick={handleSendClick}
          onpointerdown={handleSendPointerDown}
          disabled={!hasSendable || !canSend}
          class={`shrink-0 rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] text-[color:var(--color-bg)] transition-transform duration-100 active:opacity-80 disabled:bg-[color:var(--color-surface-2)] disabled:text-[color:var(--color-fg-faint)] disabled:opacity-100 ${holding ? "scale-95" : ""}`}
          aria-label={busy ? "Steer (hold to queue a follow-up)" : "Send"}
          title={hasSendable ? (activeSessionState.compacting ? "Queue until compaction finishes" : busy ? "Tap to steer · hold to queue a follow-up" : "Send · hold to queue a follow-up") : "Draft a message to send"}
        >
          <ArrowUp class="size-3.5" strokeWidth={2.5} />
        </Button>
      {/if}
    </div>
  </div>

  <CompactContextSheet bind:open={compactOpen} {hostId} {sessionId} />

  <QueuedMessagesSheet
    bind:open={queueOpen}
    {queue}
    loading={queueLoading}
    error={queueError}
    {clearing}
    onLoad={loadQueue}
    onClear={clearQueuedMessages}
  />

  <Sheet.Root bind:open={modelOpen}>
    <Sheet.BottomContent class="max-h-[82dvh]">
      <SheetHeader title="model" />
      <SessionSettingsView {hostId} {sessionId} onError={() => {}} filterKeys={["model"]} />
    </Sheet.BottomContent>
  </Sheet.Root>
</div>

{#snippet ActionFab(label: string, disabled: boolean, onClick: () => void | Promise<void>, icon: "image" | "mic")}
  <button type="button" onpointerdown={(event) => event.preventDefault()} onclick={() => void onClick()} {disabled} class="flex h-9 w-9 items-center justify-center rounded-full border border-[color:var(--color-accent)] bg-[color:var(--color-accent)] text-[color:var(--color-bg)] shadow-lg shadow-black/20 backdrop-blur-md active:opacity-85 disabled:border-[color:var(--color-border)] disabled:bg-[color:var(--color-surface)] disabled:text-[color:var(--color-fg-faint)] disabled:opacity-60" aria-label={label} title={label}>
    {#if icon === "image"}<ImagePlus class="size-4" />{:else}<Mic class="size-4" />{/if}
  </button>
{/snippet}
