// pico/src/shared/components/StatusDot.svelte
<script lang="ts">
  import type { SessionMeta } from "@pico/protocol";

  let { status, size = 6, class: className = "" }: { status: SessionMeta["status"]; size?: number; class?: string } = $props();

  const color = $derived.by(() => {
    switch (status) {
      case "thinking":
      case "tool":
        return "var(--color-accent)";
      case "waiting":
        return "var(--color-warn)";
      case "error":
        return "var(--color-danger)";
      default:
        return "var(--color-fg-faint)";
    }
  });

  const active = $derived(status === "thinking" || status === "tool");
</script>

<span
  class={`inline-block shrink-0 rounded-full ${active ? "pulse-accent" : ""} ${className}`}
  style:width={`${size}px`}
  style:height={`${size}px`}
  style:background={color}
  style:box-shadow={active ? "0 0 0 3px var(--color-accent-dim)" : "none"}
  aria-label={status}
></span>

// pi-mobile/src/components/StatusDot.tsx
import { type JSX } from "solid-js";
import type { SessionStatus } from "@pi-mobile/protocol";

interface Props {
  status: SessionStatus;
  size?: number;
  class?: string;
}

const COLOR: Record<SessionStatus, string> = {
  idle: "var(--color-fg-faint)",
  thinking: "var(--color-accent)",
  tool: "var(--color-accent)",
  waiting: "var(--color-warn)",
  error: "var(--color-danger)",
};

const isActive = (s: SessionStatus) => s === "thinking" || s === "tool";

export default function StatusDot(props: Props): JSX.Element {
  const size = () => `${props.size ?? 6}px`;
  return (
    <span
      class={props.class}
      classList={{ "pulse-accent": isActive(props.status) }}
      style={{
        display: "inline-block",
        width: size(),
        height: size(),
        "border-radius": "999px",
        background: COLOR[props.status],
        "box-shadow": isActive(props.status)
          ? "0 0 0 3px var(--color-accent-dim)"
          : "none",
      }}
    />
  );
}
