// pico/src/features/chat/components/SessionAgentActions.svelte
<script lang="ts">
  import { tick } from "svelte";
  import { MoreHorizontal } from "@lucide/svelte";
  import { createAgentActionsState } from "@/features/chat/actions/agent-actions.state.svelte";
  import { exportSessionHtml } from "@/features/chat/api";
  import { hostIssueSummary } from "@/shared/lib/host-issues";
  import AgentActionSheet from "@/features/chat/actions/AgentActionSheet.svelte";
  import AuthView from "@/features/chat/actions/AuthView.svelte";
  import MenuView from "@/features/chat/actions/MenuView.svelte";
  import SessionInfoView from "@/features/chat/actions/SessionInfoView.svelte";
  import SessionSettingsView from "@/features/chat/actions/SessionSettingsView.svelte";
  import TreeView from "@/features/chat/actions/TreeView.svelte";
  import { Button } from "@/shared/ui/button";

  let { hostId, sessionId }: { hostId: string; sessionId: string } = $props();

  const actions = createAgentActionsState();

  async function exportToHtml(): Promise<void> {
    actions.setError(null);
    actions.close();
    await tick();

    try {
      if (await exportSessionHtml(hostId, sessionId)) actions.done();
    } catch (error) {
      actions.setOpen(true);
      actions.setError(hostIssueSummary(error));
    }
  }
</script>

<Button
  type="button"
  variant="ghost"
  size="icon"
  onclick={() => actions.setOpen(true)}
  class="rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)]"
  aria-label="Agent actions"
  title="Agent actions"
>
  <MoreHorizontal class="size-4" />
</Button>

{#if actions.open}
  <AgentActionSheet
    bind:open={() => actions.open, (open) => actions.setOpen(open)}
    view={actions.view}
    error={actions.error}
    onBack={actions.back}
  >
    {#if actions.view === "menu"}
      <MenuView
        onAuth={() => actions.setView("auth")}
        onTree={() => actions.setView("tree")}
        onSettings={() => actions.setView("settings")}
        onInfo={() => actions.setView("info")}
        onExport={exportToHtml}
      />
    {:else if actions.view === "settings"}
      <SessionSettingsView {hostId} {sessionId} onError={actions.setError} excludeKeys={["model"]} />
    {:else if actions.view === "tree"}
      <TreeView {hostId} {sessionId} onDone={actions.done} onError={actions.setError} />
    {:else if actions.view === "info"}
      <SessionInfoView {hostId} {sessionId} />
    {:else if actions.view === "auth"}
      <AuthView {hostId} onError={actions.setError} />
    {/if}
  </AgentActionSheet>
{/if}

// pi-mobile/src/features/chat/components/SessionAgentActions.tsx
import { Show, createSignal } from "solid-js";
import { MoreHorizontal } from "lucide-solid";
import { haptic } from "@/lib/haptics";
import AgentActionSheet from "@/features/chat/actions/AgentActionSheet";
import AuthView from "@/features/chat/actions/AuthView";
import CompactView from "@/features/chat/actions/CompactView";
import MenuView from "@/features/chat/actions/MenuView";
import SessionInfoView from "@/features/chat/actions/SessionInfoView";
import SessionSettingsView from "@/features/chat/actions/SessionSettingsView";
import TreeView from "@/features/chat/actions/TreeView";
import type { AgentActionView } from "@/features/chat/actions/types";

interface Props {
  sessionId: string;
}

export default function SessionAgentActions(props: Props) {
  const [open, setOpen] = createSignal(false);
  const [view, setView] = createSignal<AgentActionView>("menu");
  const [error, setError] = createSignal<string | null>(null);

  function close() {
    setOpen(false);
    setView("menu");
    setError(null);
  }

  function back() {
    setView("menu");
    setError(null);
  }

  function done() {
    haptic.success();
    close();
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        class="flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)]"
        aria-label="Agent actions"
        title="Agent actions"
      >
        <MoreHorizontal size={16} />
      </button>

      <Show when={open()}>
        <AgentActionSheet view={view()} error={error()} onBack={back} onClose={close}>
          <Show when={view() === "menu"}>
            <MenuView
              onModels={() => setView("models")}
              onCompact={() => setView("compact")}
              onSettings={() => setView("settings")}
              onTree={() => setView("tree")}
              onInfo={() => setView("info")}
              onAuth={() => setView("auth")}
            />
          </Show>
          <Show when={view() === "models"}>
            <SessionSettingsView sessionId={props.sessionId} onError={setError} filterKeys={["model"]} />
          </Show>
          <Show when={view() === "compact"}>
            <CompactView sessionId={props.sessionId} onDone={done} onError={setError} />
          </Show>
          <Show when={view() === "settings"}>
            <SessionSettingsView sessionId={props.sessionId} onError={setError} />
          </Show>
          <Show when={view() === "tree"}>
            <TreeView sessionId={props.sessionId} onDone={done} onError={setError} />
          </Show>
          <Show when={view() === "info"}>
            <SessionInfoView sessionId={props.sessionId} />
          </Show>
          <Show when={view() === "auth"}>
            <AuthView onError={setError} />
          </Show>
        </AgentActionSheet>
      </Show>
    </>
  );
}
