// pi-mobile/src/features/chat/actions/SessionSettingsView.tsx
import { For, Match, Show, Switch, createResource, createSignal } from "solid-js";
import type { SessionControl } from "@pi-mobile/protocol";
import { getSessionSettings, patchSessionSetting } from "@/lib/api";
import { getBridgeUrl } from "@/lib/settings";
import { haptic } from "@/lib/haptics";
import { Segmented, SelectRows, ToggleRow } from "./shared";
import type { ActionErrorHandler } from "./types";

export default function SessionSettingsView(props: { sessionId: string; onError: ActionErrorHandler; filterKeys?: readonly string[] }) {
  const [saving, setSaving] = createSignal<string | null>(null);
  const [settings, { refetch, mutate }] = createResource(async () => {
    const baseUrl = await getBridgeUrl();
    return getSessionSettings(baseUrl, props.sessionId);
  });

  async function patch(key: string, value: string | boolean) {
    if (saving()) return;
    const prev = settings();
    setSaving(key);
    props.onError(null);
    if (prev) {
      mutate({
        ...prev,
        controls: prev.controls.map((control) => {
          if (control.key !== key) return control;
          if (control.kind === "select" && typeof value === "string") return { ...control, value };
          if (control.kind === "boolean" && typeof value === "boolean") return { ...control, value };
          return control;
        }),
      });
    }
    try {
      const baseUrl = await getBridgeUrl();
      const next = await patchSessionSetting(baseUrl, props.sessionId, key, value);
      mutate(next);
      haptic.success();
    } catch (e) {
      props.onError(String(e));
      if (prev) mutate(prev);
      await refetch();
    } finally {
      setSaving(null);
    }
  }

  return (
    <div class="flex-1 overflow-y-auto px-3 py-3">
      <Show when={settings.loading}><div class="text-[12px] text-[color:var(--color-fg-faint)]">loading settings…</div></Show>
      <Show when={settings()}>
        {(s) => (
          <div class="space-y-4">
            <For each={s().controls.filter((control) => !props.filterKeys || props.filterKeys.includes(control.key))}>{(control) => <Control control={control} saving={saving() === control.key} onChange={(value) => patch(control.key, value)} />}</For>
          </div>
        )}
      </Show>
    </div>
  );
}

function Control(props: { control: SessionControl; saving: boolean; onChange: (value: string | boolean) => void }) {
  return (
    <Switch>
      <Match when={props.control.kind === "select" && props.control}>
        {(control) => control().options.length <= 4 && control().options.every((option) => !option.description)
          ? <Segmented label={control().label} options={control().options} value={control().value} disabled={props.saving} onChange={props.onChange} />
          : <SelectRows label={control().label} options={control().options} value={control().value} disabled={props.saving} onChange={props.onChange} />}
      </Match>
      <Match when={props.control.kind === "boolean" && props.control}>
        {(control) => <ToggleRow label={control().label} checked={control().value} disabled={props.saving} onChange={props.onChange} />}
      </Match>
    </Switch>
  );
}

// pico/src/features/chat/actions/SessionSettingsView.svelte
<script lang="ts">
  import type { SessionControls } from "@pico/protocol";
  import type { ActionErrorHandler } from "./types";
  import { getSessionSettings, patchSessionSetting } from "@/features/chat/api";
  import { hostIssueSummary } from "@/shared/lib/host-issues";
  import { runOnHost } from "@/shared/lib/rpc-client";
  import { haptics } from "@/shared/mobile/haptics";
  import ActionRow from "@/shared/components/ActionRow.svelte";

  type SessionControl = SessionControls["controls"][number];

  let {
    hostId,
    sessionId,
    onError,
    filterKeys,
    excludeKeys,
  }: {
    hostId: string;
    sessionId: string;
    onError: ActionErrorHandler;
    filterKeys?: readonly string[];
    excludeKeys?: readonly string[];
  } = $props();

  let saving = $state<string | null>(null);
  let settings = $state<SessionControls | null>(null);
  let loading = $state(false);

  const visibleControls = $derived(
    (settings?.controls ?? []).filter((control: SessionControl) =>
      (!filterKeys || filterKeys.includes(control.key)) && !excludeKeys?.includes(control.key),
    ),
  );

  $effect(() => {
    void loadSettings();
  });

  async function loadSettings(): Promise<void> {
    loading = true;
    try {
      settings = await runOnHost(hostId, getSessionSettings(sessionId));
    } catch (error) {
      onError(hostIssueSummary(error));
    } finally {
      loading = false;
    }
  }

  async function patch(key: string, value: string | boolean): Promise<void> {
    if (saving) return;
    const previous = settings;
    saving = key;
    onError(null);
    if (previous) settings = patchLocal(previous, key, value);
    try {
      settings = await runOnHost(hostId, patchSessionSetting(sessionId, key, value));
      haptics.success();
    } catch (error) {
      onError(hostIssueSummary(error));
      settings = previous;
      await loadSettings();
    } finally {
      saving = null;
    }
  }

  function patchLocal(source: SessionControls, key: string, value: string | boolean): SessionControls {
    return {
      ...source,
      controls: source.controls.map((control: SessionControl) => {
        if (control.key !== key) return control;
        if (control.kind === "select" && typeof value === "string") return { ...control, value };
        if (control.kind === "boolean" && typeof value === "boolean") return { ...control, value };
        return control;
      }),
    };
  }
</script>

<div class="flex-1 overflow-y-auto px-3 py-3">
  {#if loading}<div class="type-copy text-[color:var(--color-fg-muted)]">loading settings…</div>{/if}
  {#if settings}
    <div class="space-y-4">
      {#each visibleControls as control (control.key)}
        {@render Control(control, saving === control.key, (value) => patch(control.key, value))}
      {/each}
    </div>
  {/if}
</div>

{#snippet Control(control: SessionControl, isSaving: boolean, onChange: (value: string | boolean) => void)}
  {#if control.kind === "select"}
    {#if control.options.length <= 4 && control.options.every((option: { description?: string }) => !option.description)}
      {@render Segmented(control.label, control.options, control.value, isSaving, onChange)}
    {:else}
      {@render SelectRows(control.label, control.options, control.value, isSaving, onChange)}
    {/if}
  {:else if control.kind === "boolean"}
    {@render BooleanSegmented(control.label, control.value, isSaving, onChange)}
  {/if}
{/snippet}

{#snippet BooleanSegmented(label: string, checked: boolean, disabled: boolean, onChange: (checked: boolean) => void)}
  <div>
    <div class="label mb-1.5">{label}</div>
    <div class="grid grid-cols-2 gap-1 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-bg)] p-1">
      <button type="button" disabled={disabled || !checked} onclick={() => onChange(false)} class={!checked ? "type-meta rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-2 py-2 font-medium text-[color:var(--color-bg)]" : "type-meta rounded-[var(--radius-sm)] px-2 py-2 text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)] disabled:opacity-70"}>
        off
      </button>
      <button type="button" disabled={disabled || checked} onclick={() => onChange(true)} class={checked ? "type-meta rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-2 py-2 font-medium text-[color:var(--color-bg)]" : "type-meta rounded-[var(--radius-sm)] px-2 py-2 text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)] disabled:opacity-70"}>
        on
      </button>
    </div>
  </div>
{/snippet}

{#snippet Segmented(label: string, options: readonly { value: string; label: string; description?: string; disabled?: boolean }[], value: string, disabled: boolean, onChange: (value: string) => void)}
  <div>
    <div class="label mb-1.5">{label}</div>
    <div class="grid grid-cols-2 gap-1 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-bg)] p-1">
      {#each options as option (option.value)}
        <button type="button" disabled={disabled || option.disabled || option.value === value} onclick={() => onChange(option.value)} class={option.value === value ? "type-meta rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-2 py-2 font-medium text-[color:var(--color-bg)]" : "type-meta rounded-[var(--radius-sm)] px-2 py-2 text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)] disabled:opacity-70"}>
          {option.label}
        </button>
      {/each}
    </div>
  </div>
{/snippet}

{#snippet SelectRows(label: string, options: readonly { value: string; label: string; description?: string; disabled?: boolean }[], value: string, disabled: boolean, onChange: (value: string) => void)}
  <div>
    <div class="label mb-1.5">{label}</div>
    <div class="overflow-hidden rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)]">
      {#each options as option (option.value)}
        <ActionRow disabled={disabled || option.disabled || option.value === value} onclick={() => onChange(option.value)} class="gap-3 active:bg-[color:var(--color-surface-2)]">
          <span class="min-w-0 flex-1">
            <span class="type-copy block truncate text-[color:var(--color-fg)]">{option.label}</span>
            {#if option.description}<span class="type-meta mt-0.5 block truncate text-[color:var(--color-fg-muted)]">{option.description}</span>{/if}
          </span>
          {#if option.value === value}<span class="type-meta text-[color:var(--color-accent)]">selected</span>{/if}
        </ActionRow>
      {/each}
    </div>
  </div>
{/snippet}
